name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
         # aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 780139020397.dkr.ecr.us-east-1.amazonaws.com

      #- name: Build, tag, and push image to Amazon ECR
        #run: |
          #docker build -t mediplus:v1 .
          #docker tag mediplus:v1 780139020397.dkr.ecr.us-east-1.amazonaws.com/mediplus:v1
          #docker push 780139020397.dkr.ecr.us-east-1.amazonaws.com/mediplus:v1
         
         #deploy:
 # runs-on: ubuntu-latest
 # needs: build-push
 # steps:
   # - name: Check my SSH key
     # run: |
       # echo "${{ secrets.SSH_KEY }}" > cloud-key.pem
       # chmod 600 cloud-key.pem
       # cat cloud-key.pem
       # ssh -o strictHostkeychecking=no -i cloud-key.pem ./deploy.sh ubuntu@3.90.219.251 "docker ps"
       # ssh -o strictHostkeychecking=no -i cloud-key.pem ./deploy.sh ubuntu@3.90.219.251 "hostnamectl"


deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-push

    steps:
      - name: Copy SSH key and connect to EC2
        run: |
          echo "${{ secrets.SSH_KEY }}" > cloud-key.pem
          chmod 600 cloud-key.pem
          echo "Connecting to EC2 instance..."
          
          ssh -o StrictHostKeyChecking=no -i cloud-key.pem ubuntu@3.90.219.251 "echo 'Connected to EC2'; docker ps"
          
          ssh -o StrictHostKeyChecking=no -i cloud-key.pem ubuntu@3.90.219.251 << 'EOF'
          echo "Pulling latest image from ECR..."
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 780139020397.dkr.ecr.us-east-1.amazonaws.com
          docker pull 780139020397.dkr.ecr.us-east-1.amazonaws.com/mediplus:latest
          echo "Stopping old container..."
          docker stop mediplus || true
          docker rm mediplus || true
          echo "Starting new container..."
          docker run -d -p 80:80 --name mediplus 780139020397.dkr.ecr.us-east-1.amazonaws.com/mediplus:latest
          echo "Deployment complete."
          EOF
