name: Build and Deploy to ECR and EC2

on:
  push:
    branches:
      - main

jobs:
  build-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETer login --username AWS --password-stdin $ECR_REGISTRY_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Amazon ECR
        env:
          AWS_REGION: us-east-1
          ECR_REGISTRY: 780139020397.dkr.ecr.us-east-1.amazonaws.com
        run: |
          aws ecr get-login-password --region $AWS_REGION | dock

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 780139020397.dkr.ecr.us-east-1.amazonaws.com
          IMAGE_NAME: mediplus v2
        run: |
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME:v2 $ECR_REGISTRY/$IMAGE_NAME:v2
          docker push $ECR_REGISTRY/$IMAGE_NAME:v2

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-push

    steps:
      - name: Copy SSH key and connect to EC2
        run: |
          echo "${{ secrets.SSH_KEY }}" > cloud-key.pem
          chmod 600 cloud-key.pem
          echo "Connecting to EC2 instance..."
          
          ssh -o StrictHostKeyChecking=no -i cloud-key.pem ubuntu@3.90.219.251 "echo 'Connected to EC2'; docker ps"
          
          ssh -o StrictHostKeyChecking=no -i cloud-key.pem ubuntu@3.90.219.251 << 'EOF'
          echo "Pulling latest image from ECR..."
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdiast-1.amazonaws.com/mediplus:v2
          echo "Stopping oln 780139020397.dkr.ecr.us-east-1.amazonaws.com
          docker pull 780139020397.dkr.ecr.us-ed container..."
          docker stop mediplus || true
          docker rm mediplus || true
          echo "Starting new container..."
          docker run -d -p 80:80 --name mediplus 780139020397.dkr.ecr.us-east-1.amazonaws.com/mediplus:v2
          echo "Deployment complete."
          EOF
